In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('final_demographics_data.csv')
df

,country,Region,Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15-49) newly infected with HIV,Age dependency ratio (% of working-age population),"Age dependency ratio, old (% of working-age population)","Age dependency ratio, young (% of working-age population)",Arms exports (SIPRI trend indicator values),Arms imports (SIPRI trend indicator values),"Automated teller machines (ATMs) (per 100,000 adults)",...,Population density (people per sq. km of land area),Population growth (annual %),"Population, female","Population, male","Population, total",Ratio of female to male labor force participation rate (%) (national estimate),"Total reserves (includes gold, current US$)","Unemployment, total (% of total labor force) (modeled ILO estimate)",Urban population,Women Business and the Law Index Score (scale 1-100)
0,Algeria,NorthernAfrica,1700.0,1400.0,60.067725,10.793250,49.274474,NaN,5.490000e+08,NaN,...,18.411340,1.836534,21697235,22153808,43851043,NaN,5.943439e+10,12.83,32332690,57.500
1,Argentina,SouthAmerica,5600.0,5000.0,55.767661,17.705349,38.062312,NaN,7.000000e+06,62.451861,...,16.580893,0.970054,23239321,22137442,45376763,NaN,3.940373e+10,11.67,41796990,76.250
2,Australia,Oceania,750.0,1000.0,55.051941,25.138662,29.913279,3.960000e+08,1.658000e+09,129.692233,...,3.339440,1.258698,12895213,12791828,25687041,85.979440,4.301263e+10,6.61,22152761,96.875
3,Austria,WesternEurope,NaN,NaN,50.639108,28.928737,21.710371,9.000000e+06,1.300000e+07,167.949809,...,108.061137,0.419001,4521483,4395722,8917205,84.086444,3.043956e+10,5.77,5238680,96.875
4,Bangladesh,SouthernAsia,NaN,NaN,47.018923,7.684684,39.334238,NaN,4.600000e+07,10.184245,...,1265.186932,1.002774,81430275,83259108,164689383,NaN,4.317174e+10,5.30,62873466,49.375
5,Belarus,EasternEurope,1300.0,1100.0,48.855047,23.191909,25.663139,2.300000e+07,1.300000e+07,55.859357,...,46.304370,-0.201821,5022987,4375874,9398861,NaN,7.468343e+09,5.28,7470497,75.625
6,Belgium,WesternEurope,NaN,NaN,56.956811,30.220836,26.735975,5.300000e+07,8.600000e+07,NaN,...,381.637946,0.581621,5828325,5727672,11555997,84.356300,3.329623e+10,6.01,11334006,100.000
7,Brazil,SouthAmerica,48000.0,NaN,43.475056,13.762521,29.712535,1.700000e+08,1.580000e+08,96.555087,...,25.431425,0.712873,108123626,104435783,212559409,70.792152,3.556140e+11,13.67,185081854,85.000
8,Canada,NorthernAmerica,NaN,NaN,51.239287,27.380909,23.858378,2.000000e+08,2.070000e+08,210.232386,...,4.239011,1.089591,19142488,18862750,38005238,86.700655,9.042814e+10,9.48,30997832,100.000
9,Chile,SouthAmerica,5000.0,4400.0,45.945748,17.867638,28.078110,NaN,2.930000e+08,49.467263,...,25.710002,0.862530,9690540,9425669,19116209,67.032636,3.916612e+10,11.51,16770077,80.000
10,China,EasternAsia,NaN,NaN,42.207229,17.019747,25.187482,7.600000e+08,8.110000e+08,87.876942,...,148.769889,0.314091,682951049,719160951,1402112000,NaN,3.357240e+12,5.00,861289359,75.625
11,Colombia,SouthAmerica,9300.0,8500.0,45.442131,13.177874,32.264257,4.000000e+06,7.700000e+07,41.148881,...,45.861094,1.073767,25898320,24984564,50882884,66.236333,5.849948e+10,15.44,41431388,81.875
12,Denmark,NorthernEurope,200.0,200.0,57.345835,31.727201,25.618634,NaN,6.500000e+07,42.564959,...,145.785100,0.291641,2932556,2898848,5831404,86.985992,7.282335e+10,5.66,5138400,100.000
13,Ecuador,SouthAmerica,2100.0,1800.0,53.805972,11.675554,42.130419,NaN,2.300000e+07,NaN,...,71.038251,1.538741,8819233,8823827,17643060,67.003320,6.569461e+09,6.23,11320846,89.375
14,Egypt,NorthernAfrica,3300.0,2900.0,64.616390,8.776821,55.839569,NaN,1.311000e+09,22.061023,...,102.802153,1.920248,50631541,51702862,102334403,NaN,3.897281e+10,10.45,43781728,45.000
15,Ethiopia,EasternAfrica,12000.0,8500.0,76.848827,6.254955,70.593872,NaN,NaN,NaN,...,101.800711,2.541386,57446748,57516835,114963583,NaN,3.046114e+09,2.79,24941349,76.875
16,France,WesternEurope,NaN,NaN,62.356406,33.694564,28.661841,1.995000e+09,1.450000e+08,93.522775,...,123.076834,0.211907,34777344,32614238,67391582,86.090801,2.242360e+11,8.62,54570334,100.000
17,Germany,WesternEurope,2600.0,2200.0,55.383362,33.698689,21.684674,1.232000e+09,3.300000e+07,NaN,...,238.252118,0.177430,42093236,41147289,83240525,85.420111,2.684090e+11,4.31,64472284,97.500
18,Ghana,WesternAfrica,19000.0,14000.0,67.424279,5.257707,62.166572,NaN,NaN,NaN,...,136.560363,2.130763,15322946,15749999,31072945,NaN,7.884092e+09,4.53,17820023,75.000
19,Greece,SouthernEurope,980.0,1000.0,56.104419,34.786921,21.317498,1.700000e+07,8.500000e+07,63.876410,...,83.130714,-0.056286,5456162,5259387,10715549,73.670843,1.193118e+10,16.85,8541900,97.500
20,India,SouthernAsia,NaN,NaN,48.664620,9.773047,38.891574,1.510000e+08,2.799000e+09,21.496549,...,464.149410,0.989414,662903415,717100970,1380004385,NaN,5.902270e+11,7.11,481980332,74.375
21,Indonesia,South-easternAsia,28000.0,24000.0,47.489405,9.236544,38.252862,NaN,2.700000e+08,51.659937,...,145.683544,1.065179,135805760,137717861,273523621,65.236052,1.359160e+11,4.11,154926514,64.375
22,Iraq,WesternAsia,NaN,NaN,69.942237,5.850652,64.091585,NaN,1.000000e+06,NaN,...,92.651253,2.295304,19864725,20357778,40222503,NaN,6.534004e+10,13.74,28514939,45.000
23,Ireland,NorthernEurope,500.0,500.0,54.823236,22.570047,32.253189,NaN,1.100000e+07,NaN,...,72.502889,1.216323,2515113,2479611,4994724,81.775007,7.463045e+09,5.92,3179292,100.000
24,Israel,WesternAsia,NaN,NaN,67.343893,20.774652,46.569240,3.450000e+08,4.740000e+08,133.298697,...,425.919593,1.783211,4629378,4587522,9216900,NaN,1.732920e+11,4.61,8533651,80.625
25,Italy,SouthernEurope,2500.0,2200.0,56.959220,36.574470,20.384750,8.060000e+08,1.310000e+08,90.307582,...,200.026947,-0.293517,30558291,28995732,59554023,68.927336,2.106870e+11,9.31,42306582,97.500
26,Japan,EasternAsia,600.0,1000.0,69.049789,48.005531,21.044258,NaN,7.240000e+08,121.705069,...,345.229138,-0.340269,64395674,61440347,125836021,74.509804,1.390810e+12,2.97,115494817,81.875
27,Kazakhstan,CentralAsia,3700.0,3200.0,58.848597,12.553489,46.295109,NaN,2.680000e+08,95.781246,...,6.946861,1.292098,9652308,9102132,18754440,84.370861,3.563810e+10,6.05,10815873,69.375
28,Kenya,EasternAfrica,33000.0,27000.0,69.775801,4.259991,65.515810,NaN,6.000000e+07,7.304405,...,94.478160,2.251879,27052773,26718527,53771300,NaN,8.297264e+09,2.98,15053275,80.625
29,Malaysia,South-easternAsia,6100.0,5700.0,44.158282,10.355875,33.802407,NaN,5.500000e+07,55.564121,...,98.511636,1.294285,15735185,16630813,32365998,NaN,1.076440e+11,4.55,24973604,50.000
30,Mexico,CentralAmerica,20000.0,18000.0,50.270568,11.447768,38.822800,NaN,2.570000e+08,62.134871,...,66.325139,1.058240,65861267,63071486,128932753,57.136872,1.990690e+11,4.71,104088701,88.750
31,Morocco,NorthernAfrica,720.0,1000.0,52.380107,11.591013,40.789094,NaN,7.000000e+06,28.612290,...,82.703469,1.195921,18593671,18316887,36910558,NaN,3.599764e+10,10.15,23450016,75.625
32,Nepal,SouthernAsia,750.0,1000.0,52.993769,8.916702,44.077067,NaN,NaN,19.795033,...,203.256421,1.829086,15788373,13348435,29136808,NaN,1.146780e+10,4.44,5995190,80.625
33,Netherlands,WesternEurope,500.0,500.0,55.609277,31.176040,24.433236,4.880000e+08,6.100000e+08,36.027663,...,518.002346,0.553471,8751402,8689737,17441139,86.381997,5.397140e+10,4.09,16087009,97.500
34,Nigeria,WesternAfrica,86000.0,61000.0,85.962352,5.091768,80.870584,NaN,1.250000e+08,NaN,...,226.335504,2.542973,101669950,104469637,206139587,NaN,3.672957e+10,9.01,107106007,63.125
35,Norway,NorthernEurope,100.0,100.0,53.335836,26.874528,26.461308,7.200000e+07,4.500000e+08,NaN,...,14.733934,0.588757,2660602,2718873,5379475,94.584287,7.525881e+10,4.62,4463566,96.875
36,Pakistan,SouthernAsia,25000.0,22000.0,64.387741,7.148647,57.239094,NaN,7.590000e+08,NaN,...,286.545676,1.978320,107220324,113672007,220892331,NaN,1.852173e+10,4.65,82094635,55.625
37,Peru,SouthAmerica,4100.0,3700.0,50.189391,13.104418,37.084973,NaN,1.900000e+07,124.295259,...,25.759255,1.409210,16593240,16378606,32971846,76.571502,NaN,6.24,25815966,95.000
38,Philippines,South-easternAsia,17000.0,16000.0,55.169455,8.552395,46.617060,NaN,3.490000e+08,29.716935,...,367.512107,1.345430,54552260,55028825,109581085,NaN,1.099900e+11,3.36,51950201,78.750
39,Poland,EasternEurope,NaN,NaN,51.416859,28.374688,23.042171,1.300000e+07,1.930000e+08,67.843417,...,123.953366,-0.038656,19562432,18388370,37950802,73.624347,1.542190e+11,3.55,22786800,93.750
40,Portugal,SouthernEurope,670.0,1000.0,55.826904,35.485325,20.341579,4.600000e+07,4.700000e+07,165.273853,...,112.499280,0.187463,5430030,4875534,10305564,85.003171,2.945981e+10,7.20,6833619,100.000
41,Romania,EasternEurope,770.0,1000.0,53.260252,29.473349,23.786903,NaN,1.870000e+08,62.794601,...,83.823553,-0.442473,9908658,9377465,19286123,69.290737,5.219056e+10,4.84,10451921,90.625
42,Saudi Arabia,WesternAsia,1000.0,1000.0,39.265467,4.872146,34.393321,NaN,2.466000e+09,NaN,...,16.194831,1.578837,14682559,20131308,34813867,NaN,4.728510e+11,8.22,29343564,80.000
43,Singapore,South-easternAsia,100.0,100.0,34.503907,17.958348,16.545559,NaN,7.400000e+07,54.007050,...,8019.473907,-0.311905,2709673,2976134,5685807,NaN,3.698340e+11,5.19,5685807,82.500
44,South Africa,SouthernAfrica,230000.0,200000.0,52.231479,8.387100,43.844379,3.700000e+07,NaN,58.587941,...,48.890593,1.273356,30092678,29216012,59308690,76.740947,5.500849e+10,28.74,39946775,88.125
45,Spain,SouthernEurope,3500.0,3200.0,52.385779,30.443039,21.942740,1.201000e+09,5.700000e+07,103.401671,...,94.778297,0.461547,24079931,23271636,47351567,83.150773,8.128770e+10,15.67,38264801,97.500
46,Sri Lanka,SouthernAsia,200.0,200.0,53.651625,17.259469,36.392157,NaN,NaN,NaN,...,354.309453,0.530627,11409149,10509851,21919000,NaN,5.663994e+09,4.84,4101702,65.625
47,Sweden,NorthernEurope,NaN,NaN,61.166545,32.763232,28.403313,2.860000e+08,3.000000e+06,NaN,...,25.419071,0.722704,5167175,5186267,10353442,92.508871,5.826034e+10,8.45,9108648,100.000
48,Switzerland,WesternEurope,NaN,NaN,51.644210,28.960320,22.683891,1.790000e+08,1.000000e+07,93.955903,...,218.566895,0.715961,4352040,4284856,8636896,85.175092,1.083400e+12,4.94,6383962,85.625
49,Thailand,South-easternAsia,6600.0,6500.0,41.864563,18.382438,23.482125,NaN,1.320000e+08,NaN,...,136.624279,0.250165,35833918,33966060,69799978,78.470105,2.581040e+11,1.02,35898129,78.125
50,Tunisia,NorthernAfrica,500.0,500.0,49.619142,13.275631,36.343511,NaN,1.500000e+07,NaN,...,76.072464,1.053854,5957866,5860752,11818618,NaN,9.810631e+09,16.69,8221976,67.500
51,Turkey,WesternAsia,NaN,NaN,49.082672,13.389213,35.693459,1.410000e+08,8.600000e+07,NaN,...,109.583913,1.084194,42702942,41636125,84339067,45.246479,9.351156e+10,13.92,64186247,82.500
52,Uganda,EasternAfrica,38000.0,31000.0,92.313546,3.818770,88.494776,NaN,1.300000e+07,NaN,...,228.111909,3.269713,23194411,22546589,45741000,NaN,NaN,2.44,11414209,73.125
53,Ukraine,EasternEurope,9300.0,8500.0,49.119436,25.274466,23.844970,1.150000e+08,1.800000e+07,93.739228,...,76.173098,-0.568252,23685780,20448913,44134693,NaN,2.913754e+10,9.48,30721277,79.375
54,United Arab Emirates,WesternAsia,100.0,100.0,19.158962,1.506655,17.652307,1.910000e+08,4.320000e+08,52.485227,...,139.262180,1.219429,3054051,6836349,9890400,NaN,1.067020e+11,5.00,8609395,82.500
55,United States of America,NorthernAmerica,NaN,NaN,53.852481,25.587092,28.265389,9.372000e+09,6.870000e+08,NaN,...,36.019350,0.350911,166449500,163034623,329484123,83.062371,6.283700e+11,8.31,272364755,91.250
56,Viet Nam,South-easternAsia,6100.0,5300.0,45.053772,11.409946,33.643826,NaN,4.100000e+07,26.264738,...,313.924543,0.904518,48740329,48598254,97338583,82.655502,9.483362e+10,2.27,36346227,81.875

In [4]:
df.isnull().sum().head(10)

country                                                                0
Region                                                                 0
Adults (ages 15+) and children (ages 0-14) newly infected with HIV    14
Adults (ages 15-49) newly infected with HIV                           15
Age dependency ratio (% of working-age population)                     0
Age dependency ratio, old (% of working-age population)                0
Age dependency ratio, young (% of working-age population)              0
Arms exports (SIPRI trend indicator values)                           31
Arms imports (SIPRI trend indicator values)                            5
Automated teller machines (ATMs) (per 100,000 adults)                 19
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 61 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   country                                                                         57 non-null     object
 1   Region                                                                          57 non-null     object
 2   Adults (ages 15+) and children (ages 0-14) newly infected with HIV              43 non-null     float64
 3   Adults (ages 15-49) newly infected with HIV                                     42 non-null     float64
 4   Age dependency ratio (% of working-age population)                              57 non-null     float64
 5   Age dependency ratio, old (% of working-age population)                         57 non-null     float64
 6   Age dependency ratio, young (% of working-age population)                       57 non-null     float64
 7   Arms exports (SIPRI trend indicator values)                                     26 non-null     float64
 8   Arms imports (SIPRI trend indicator values)                                     52 non-null     float64
 9   Automated teller machines (ATMs) (per 100,000 adults)                           38 non-null     float64
 10  Average transaction cost of sending remittances from a specific country (%)     30 non-null     float64
 11  Average transaction cost of sending remittances to a specific country (%)       32 non-null     float64
 12  Bank capital to assets ratio (%)                                                43 non-null     float64
 13  Bank liquid reserves to bank assets ratio (%)                                   36 non-null     float64
 14  Bank nonperforming loans to total gross loans (%)                               44 non-null     float64
 15  Charges for the use of intellectual property, payments (BoP, current US$)       44 non-null     float64
 16  Charges for the use of intellectual property, receipts (BoP, current US$)       44 non-null     float64
 17  Commercial bank branches (per 100,000 adults)                                   41 non-null     float64
 18  Computer, communications and other services (% of commercial service exports)   46 non-null     float64
 19  Computer, communications and other services (% of commercial service imports)   46 non-null     float64
 20  Consumer price index (2010 = 100)                                               53 non-null     float64
 21  Domestic credit provided by financial sector (% of GDP)                         12 non-null     float64
 22  Domestic credit to private sector (% of GDP)                                    42 non-null     float64
 23  Domestic credit to private sector by banks (% of GDP)                           47 non-null     float64
 24  Employment to population ratio, 15+, female (%) (national estimate)             36 non-null     float64
 25  Employment to population ratio, 15+, male (%) (national estimate)               36 non-null     float64
 26  Employment to population ratio, 15+, total (%) (national estimate)              36 non-null     float64
 27  Employment to population ratio, ages 15-24, female (%) (national estimate)      35 non-null     float64
 28  Employment to population ratio, ages 15-24, male (%) (national estimate)        35 non-null     float64
 29  Employment to population ratio, ages 15-24, total (%) (national estimate)       35 non-null     float64
 30  Final consumption expenditure (% of GDP)                                        48 non-null     float64
 31  Final consumption expenditure (annual % growth)                                 47 non-null     float64
 32  Final consumption expenditure (constant 2010 US$)                               46 non-null     float64
 33  Final consumption expenditure (constant LCU)                                    47 non-null     float64
 34  Final consumption expenditure (current LCU)                                     48 non-null     float64
 35  Final consumption expenditure (current US$)                                     48 non-null     float64
 36  Fixed broadband subscriptions                                                   53 non-null     float64
 37  Fixed broadband subscriptions (per 100 people)                                  53 non-null     float64
 38  Fixed telephone subscriptions                                                   53 non-null     float64
 39  Fixed telephone subscriptions (per 100 people)                                  53 non-null     float64
 40  GDP (constant 2010 US$)                                                         55 non-null     float64
 41  GDP growth (annual %)                                                           55 non-null     float64
 42  GDP per capita (constant 2010 US$)                                              55 non-null     float64
 43  GNI (constant 2010 US$)                                                         34 non-null     float64
 44  GNI growth (annual %)                                                           35 non-null     float64
 45  GNI per capita (constant 2010 US$)                                              34 non-null     float64
 46  High-technology exports (current US$)                                           42 non-null     float64
 47  Human capital index (HCI) (scale 0-1)                                           57 non-null     float64
 48  Individuals using the Internet (% of population)                                29 non-null     float64
 49  Labor force, total                                                              57 non-null     int64
 50  Military expenditure (% of GDP)                                                 55 non-null     float64
 51  Population density (people per sq. km of land area)                             57 non-null     float64
 52  Population growth (annual %)                                                    57 non-null     float64
 53  Population, female                                                              57 non-null     int64
 54  Population, male                                                                57 non-null     int64
 55  Population, total                                                               57 non-null     int64
 56  Ratio of female to male labor force participation rate (%) (national estimate)  32 non-null     float64
 57  Total reserves (includes gold, current US$)                                     55 non-null     float64
 58  Unemployment, total (% of total labor force) (modeled ILO estimate)             57 non-null     float64
 59  Urban population                                                                57 non-null     int64
 60  Women Business and the Law Index Score (scale 1-100)                            57 non-null     float64
dtypes: float64(54), int64(5), object(2)
memory usage: 27.3+ KB

In [6]:
df.describe()

,Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15-49) newly infected with HIV,Age dependency ratio (% of working-age population),"Age dependency ratio, old (% of working-age population)","Age dependency ratio, young (% of working-age population)",Arms exports (SIPRI trend indicator values),Arms imports (SIPRI trend indicator values),"Automated teller machines (ATMs) (per 100,000 adults)",Average transaction cost of sending remittances from a specific country (%),Average transaction cost of sending remittances to a specific country (%),...,Population density (people per sq. km of land area),Population growth (annual %),"Population, female","Population, male","Population, total",Ratio of female to male labor force participation rate (%) (national estimate),"Total reserves (includes gold, current US$)","Unemployment, total (% of total labor force) (modeled ILO estimate)",Urban population,Women Business and the Law Index Score (scale 1-100)
count,43.000000,42.000000,57.000000,57.000000,57.000000,2.600000e+01,5.200000e+01,38.000000,30.000000,32.000000,...,57.000000,57.000000,5.700000e+01,5.700000e+01,5.700000e+01,32.000000,5.500000e+01,57.000000,5.700000e+01,57.000000
mean,14819.534884,11840.476190,54.549532,18.407427,36.142105,7.039231e+08,3.348077e+08,73.407803,8.053924,6.045787,...,298.998842,0.964436,5.367960e+07,5.507711e+07,1.087567e+08,77.774286,2.116366e+11,7.568421,6.134836e+07,81.611842
std,37391.501833,31926.058319,11.447176,10.895289,15.854687,1.832161e+09,5.732273e+08,46.711933,3.550078,2.194585,...,1058.817694,0.829137,1.241665e+08,1.322738e+08,2.564180e+08,10.649954,5.020306e+11,4.844729,1.319933e+08,14.995324
min,100.000000,100.000000,19.158962,1.506655,16.545559,4.000000e+06,1.000000e+06,7.304405,3.311032,1.398000,...,3.339440,-0.568252,2.515113e+06,2.479611e+06,4.994724e+06,45.246479,3.046114e+09,1.020000,3.179292e+06,45.000000
25%,735.000000,1000.000000,49.082672,9.236544,23.858378,4.775000e+07,3.050000e+07,41.502901,5.393122,4.560220,...,48.890593,0.350911,8.751402e+06,8.689737e+06,1.744114e+07,70.416798,3.186789e+10,4.610000,9.108648e+06,75.625000
50%,3300.000000,2550.000000,53.335836,17.019747,32.264257,1.745000e+08,1.055000e+08,62.293366,7.388989,6.262878,...,102.802153,1.002774,1.956243e+07,2.013131e+07,3.800524e+07,82.215255,5.849948e+10,5.920000,2.497360e+07,81.875000
75%,10650.000000,8500.000000,57.345835,28.374688,42.130419,4.650000e+08,3.697500e+08,95.324910,9.714427,7.298802,...,218.566895,1.345430,4.270294e+07,4.163612e+07,8.433907e+07,85.236347,1.637555e+11,9.480000,4.378173e+07,96.875000
max,230000.000000,200000.000000,92.313546,48.005531,88.494776,9.372000e+09,2.799000e+09,210.232386,16.096088,10.905730,...,8019.473907,3.269713,6.829510e+08,7.191610e+08,1.402112e+09,94.584287,3.357240e+12,28.740000,8.612894e+08,100.000000

### Filling NAN Values

#### 1.Adults and children newly infected

In [7]:
df. fillna({'Adults (ages 15+) and children (ages 0-14) newly infected with HIV':df['Adults (ages 15+) and children (ages 0-14) newly infected with HIV'].mean()},inplace=True)

In [8]:
df.isnull().sum()

country                                                                            0
Region                                                                             0
Adults (ages 15+) and children (ages 0-14) newly infected with HIV                 0
Adults (ages 15-49) newly infected with HIV                                       15
Age dependency ratio (% of working-age population)                                 0
                                                                                  ..
Ratio of female to male labor force participation rate (%) (national estimate)    25
Total reserves (includes gold, current US$)                                        2
Unemployment, total (% of total labor force) (modeled ILO estimate)                0
Urban population                                                                   0
Women Business and the Law Index Score (scale 1-100)                               0
Length: 61, dtype: int64

#### Filling Adults newly infected with HIV

In [9]:
df.fillna({"Adults (ages 15-49) newly infected with HIV":df['Adults (ages 15-49) newly infected with HIV'].mean()},inplace=True)

In [10]:
df.isnull().sum()

country                                                                            0
Region                                                                             0
Adults (ages 15+) and children (ages 0-14) newly infected with HIV                 0
Adults (ages 15-49) newly infected with HIV                                        0
Age dependency ratio (% of working-age population)                                 0
                                                                                  ..
Ratio of female to male labor force participation rate (%) (national estimate)    25
Total reserves (includes gold, current US$)                                        2
Unemployment, total (% of total labor force) (modeled ILO estimate)                0
Urban population                                                                   0
Women Business and the Law Index Score (scale 1-100)                               0
Length: 61, dtype: int64

#### Filling Ratio of female to male labor force participation rate (%) (national estimate)

In [11]:
df.fillna({"Ratio of female to male labor force participation rate (%) (national estimate)":df["Ratio of female to male labor force participation rate (%) (national estimate)"].median()},inplace=True)

In [12]:
df.isnull().sum()

country                                                                           0
Region                                                                            0
Adults (ages 15+) and children (ages 0-14) newly infected with HIV                0
Adults (ages 15-49) newly infected with HIV                                       0
Age dependency ratio (% of working-age population)                                0
                                                                                 ..
Ratio of female to male labor force participation rate (%) (national estimate)    0
Total reserves (includes gold, current US$)                                       2
Unemployment, total (% of total labor force) (modeled ILO estimate)               0
Urban population                                                                  0
Women Business and the Law Index Score (scale 1-100)                              0
Length: 61, dtype: int64

#### Filling Total reserves (includes gold, current US$)

In [13]:
df.fillna({"Total reserves (includes gold, current US$)":df["Total reserves (includes gold, current US$)"].median()},inplace=True)

In [14]:
df.isnull().sum()

country                                                                           0
Region                                                                            0
Adults (ages 15+) and children (ages 0-14) newly infected with HIV                0
Adults (ages 15-49) newly infected with HIV                                       0
Age dependency ratio (% of working-age population)                                0
                                                                                 ..
Ratio of female to male labor force participation rate (%) (national estimate)    0
Total reserves (includes gold, current US$)                                       0
Unemployment, total (% of total labor force) (modeled ILO estimate)               0
Urban population                                                                  0
Women Business and the Law Index Score (scale 1-100)                              0
Length: 61, dtype: int64

In [15]:
df.isna()

,country,Region,Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15-49) newly infected with HIV,Age dependency ratio (% of working-age population),"Age dependency ratio, old (% of working-age population)","Age dependency ratio, young (% of working-age population)",Arms exports (SIPRI trend indicator values),Arms imports (SIPRI trend indicator values),"Automated teller machines (ATMs) (per 100,000 adults)",...,Population density (people per sq. km of land area),Population growth (annual %),"Population, female","Population, male","Population, total",Ratio of female to male labor force participation rate (%) (national estimate),"Total reserves (includes gold, current US$)","Unemployment, total (% of total labor force) (modeled ILO estimate)",Urban population,Women Business and the Law Index Score (scale 1-100)
0,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
52,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
53,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
df.isna().count()

country                                                                           57
Region                                                                            57
Adults (ages 15+) and children (ages 0-14) newly infected with HIV                57
Adults (ages 15-49) newly infected with HIV                                       57
Age dependency ratio (% of working-age population)                                57
                                                                                  ..
Ratio of female to male labor force participation rate (%) (national estimate)    57
Total reserves (includes gold, current US$)                                       57
Unemployment, total (% of total labor force) (modeled ILO estimate)               57
Urban population                                                                  57
Women Business and the Law Index Score (scale 1-100)                              57
Length: 61, dtype: int64

In [17]:
df.isnull()

,country,Region,Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15-49) newly infected with HIV,Age dependency ratio (% of working-age population),"Age dependency ratio, old (% of working-age population)","Age dependency ratio, young (% of working-age population)",Arms exports (SIPRI trend indicator values),Arms imports (SIPRI trend indicator values),"Automated teller machines (ATMs) (per 100,000 adults)",...,Population density (people per sq. km of land area),Population growth (annual %),"Population, female","Population, male","Population, total",Ratio of female to male labor force participation rate (%) (national estimate),"Total reserves (includes gold, current US$)","Unemployment, total (% of total labor force) (modeled ILO estimate)",Urban population,Women Business and the Law Index Score (scale 1-100)
0,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
52,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
53,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

#### FIlling Arms exports (SIPRI trend indicator values)

In [18]:
df.fillna({"Arms exports (SIPRI trend indicator values)":df['Arms exports (SIPRI trend indicator values)'].median()},inplace=True)

In [19]:
df.isnull().sum()

country                                                                           0
Region                                                                            0
Adults (ages 15+) and children (ages 0-14) newly infected with HIV                0
Adults (ages 15-49) newly infected with HIV                                       0
Age dependency ratio (% of working-age population)                                0
                                                                                 ..
Ratio of female to male labor force participation rate (%) (national estimate)    0
Total reserves (includes gold, current US$)                                       0
Unemployment, total (% of total labor force) (modeled ILO estimate)               0
Urban population                                                                  0
Women Business and the Law Index Score (scale 1-100)                              0
Length: 61, dtype: int64

In [20]:
df.fillna({'Arms exports (SIPRI trend indicator values)':df['Arms exports (SIPRI trend indicator values)'].mean()},inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 61 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   country                                                                         57 non-null     object
 1   Region                                                                          57 non-null     object
 2   Adults (ages 15+) and children (ages 0-14) newly infected with HIV              57 non-null     float64
 3   Adults (ages 15-49) newly infected with HIV                                     57 non-null     float64
 4   Age dependency ratio (% of working-age population)                              57 non-null     float64
 5   Age dependency ratio, old (% of working-age population)                         57 non-null     float64
 6   Age dependency ratio, young (% of working-age population)                       57 non-null     float64
 7   Arms exports (SIPRI trend indicator values)                                     57 non-null     float64
 8   Arms imports (SIPRI trend indicator values)                                     52 non-null     float64
 9   Automated teller machines (ATMs) (per 100,000 adults)                           38 non-null     float64
 10  Average transaction cost of sending remittances from a specific country (%)     30 non-null     float64
 11  Average transaction cost of sending remittances to a specific country (%)       32 non-null     float64
 12  Bank capital to assets ratio (%)                                                43 non-null     float64
 13  Bank liquid reserves to bank assets ratio (%)                                   36 non-null     float64
 14  Bank nonperforming loans to total gross loans (%)                               44 non-null     float64
 15  Charges for the use of intellectual property, payments (BoP, current US$)       44 non-null     float64
 16  Charges for the use of intellectual property, receipts (BoP, current US$)       44 non-null     float64
 17  Commercial bank branches (per 100,000 adults)                                   41 non-null     float64
 18  Computer, communications and other services (% of commercial service exports)   46 non-null     float64
 19  Computer, communications and other services (% of commercial service imports)   46 non-null     float64
 20  Consumer price index (2010 = 100)                                               53 non-null     float64
 21  Domestic credit provided by financial sector (% of GDP)                         12 non-null     float64
 22  Domestic credit to private sector (% of GDP)                                    42 non-null     float64
 23  Domestic credit to private sector by banks (% of GDP)                           47 non-null     float64
 24  Employment to population ratio, 15+, female (%) (national estimate)             36 non-null     float64
 25  Employment to population ratio, 15+, male (%) (national estimate)               36 non-null     float64
 26  Employment to population ratio, 15+, total (%) (national estimate)              36 non-null     float64
 27  Employment to population ratio, ages 15-24, female (%) (national estimate)      35 non-null     float64
 28  Employment to population ratio, ages 15-24, male (%) (national estimate)        35 non-null     float64
 29  Employment to population ratio, ages 15-24, total (%) (national estimate)       35 non-null     float64
 30  Final consumption expenditure (% of GDP)                                        48 non-null     float64
 31  Final consumption expenditure (annual % growth)                                 47 non-null     float64
 32  Final consumption expenditure (constant 2010 US$)                               46 non-null     float64
 33  Final consumption expenditure (constant LCU)                                    47 non-null     float64
 34  Final consumption expenditure (current LCU)                                     48 non-null     float64
 35  Final consumption expenditure (current US$)                                     48 non-null     float64
 36  Fixed broadband subscriptions                                                   53 non-null     float64
 37  Fixed broadband subscriptions (per 100 people)                                  53 non-null     float64
 38  Fixed telephone subscriptions                                                   53 non-null     float64
 39  Fixed telephone subscriptions (per 100 people)                                  53 non-null     float64
 40  GDP (constant 2010 US$)                                                         55 non-null     float64
 41  GDP growth (annual %)                                                           55 non-null     float64
 42  GDP per capita (constant 2010 US$)                                              55 non-null     float64
 43  GNI (constant 2010 US$)                                                         34 non-null     float64
 44  GNI growth (annual %)                                                           35 non-null     float64
 45  GNI per capita (constant 2010 US$)                                              34 non-null     float64
 46  High-technology exports (current US$)                                           42 non-null     float64
 47  Human capital index (HCI) (scale 0-1)                                           57 non-null     float64
 48  Individuals using the Internet (% of population)                                29 non-null     float64
 49  Labor force, total                                                              57 non-null     int64
 50  Military expenditure (% of GDP)                                                 55 non-null     float64
 51  Population density (people per sq. km of land area)                             57 non-null     float64
 52  Population growth (annual %)                                                    57 non-null     float64
 53  Population, female                                                              57 non-null     int64
 54  Population, male                                                                57 non-null     int64
 55  Population, total                                                               57 non-null     int64
 56  Ratio of female to male labor force participation rate (%) (national estimate)  57 non-null     float64
 57  Total reserves (includes gold, current US$)                                     57 non-null     float64
 58  Unemployment, total (% of total labor force) (modeled ILO estimate)             57 non-null     float64
 59  Urban population                                                                57 non-null     int64
 60  Women Business and the Law Index Score (scale 1-100)                            57 non-null     float64
dtypes: float64(54), int64(5), object(2)
memory usage: 27.3+ KB

#### Filling Arms imports (SIPRI trend indicator values)

In [22]:
df.fillna({"Arms imports (SIPRI trend indicator values":df["Arms imports (SIPRI trend indicator values)"].median()},inplace=True)

In [23]:
df.fillna(
    {
        "Adults (ages 15+) and children (ages 0-14) newly infected with HIV":df['Adults (ages 15+) and children (ages 0-14) newly infected with HIV'].median(),
        "Adults (ages 15-49) newly infected with HIV":df['Adults (ages 15-49) newly infected with HIV'].median(),
        "Arms exports (SIPRI trend indicator values)":df['Arms exports (SIPRI trend indicator values)'].median(),
        "Automated teller machines (ATMs) (per 100,000 adults)":df['Automated teller machines (ATMs) (per 100,000 adults)'].mean(),
        "Arms imports (SIPRI trend indicator values)":df['Arms imports (SIPRI trend indicator values)'].median()
    },inplace=True 
)

In [24]:
df.fillna(
    {
        "Average transaction cost of sending remittances from a specific country (%)":df['Average transaction cost of sending remittances from a specific country (%)'].mean(),
        "Average transaction cost of sending remittances to a specific country (%)":df['Average transaction cost of sending remittances to a specific country (%)'].median(),
        "Bank capital to assets ratio (%)":df['Bank capital to assets ratio (%)'].median(),
        "Bank liquid reserves to bank assets ratio (%)":df['Bank liquid reserves to bank assets ratio (%)'].median(),
        "Bank nonperforming loans to total gross loans (%)":df['Bank nonperforming loans to total gross loans (%)'].median(),
        "Charges for the use of intellectual property, payments (BoP, current US$)":df['Charges for the use of intellectual property, payments (BoP, current US$)'].median(),
        "Charges for the use of intellectual property, receipts (BoP, current US$)":df['Charges for the use of intellectual property, receipts (BoP, current US$)'].median(), 
        "Commercial bank branches (per 100,000 adults)":df["Commercial bank branches (per 100,000 adults)"].median(),
        "Computer, communications and other services (% of commercial service exports)":df["Computer, communications and other services (% of commercial service exports)"].mean(),
        "Computer, communications and other services (% of commercial service imports)":df["Computer, communications and other services (% of commercial service imports)"].mean()
         
     },inplace=True
)

In [25]:
df.fillna(
    {
        "Consumer price index (2010 = 100)":df['Consumer price index (2010 = 100)'].median(),
        "Domestic credit provided by financial sector (% of GDP)":df['Domestic credit provided by financial sector (% of GDP)'].median(),
        "Domestic credit to private sector (% of GDP)":df['Domestic credit to private sector (% of GDP)'].median(),
        "Domestic credit to private sector by banks (% of GDP)":df['Domestic credit to private sector by banks (% of GDP)'].median(),
        "Employment to population ratio, 15+, female (%) (national estimate)":df['Employment to population ratio, 15+, female (%) (national estimate)'].mean(),
        "Employment to population ratio, 15+, male (%) (national estimate)":df["Employment to population ratio, 15+, male (%) (national estimate)"].median(),
        "Employment to population ratio, 15+, total (%) (national estimate)":df["Employment to population ratio, 15+, total (%) (national estimate)"].mean(),
        "Employment to population ratio, ages 15-24, female (%) (national estimate)":df["Employment to population ratio, ages 15-24, female (%) (national estimate)"].median(),
        "Employment to population ratio, ages 15-24, male (%) (national estimate)":df["Employment to population ratio, ages 15-24, male (%) (national estimate)"].mean(),
        "Employment to population ratio, ages 15-24, total (%) (national estimate)":df["Employment to population ratio, ages 15-24, total (%) (national estimate)"].mean()
    },inplace=True
)

In [26]:
df.fillna(
    {
        
        "Final consumption expenditure (% of GDP)":df['Final consumption expenditure (% of GDP)'].median(),
        "Final consumption expenditure (annual % growth)":df['Final consumption expenditure (annual % growth)'].median(),
        "Final consumption expenditure (constant 2010 US$)":df['Final consumption expenditure (constant 2010 US$)'].median(),
        'Final consumption expenditure (constant LCU)':df['Final consumption expenditure (constant LCU)'].median(),
        'Final consumption expenditure (current LCU)':df['Final consumption expenditure (current LCU)'].mean(),
        'Final consumption expenditure (current US$)':df['Final consumption expenditure (current US$)'].median(),
        'Fixed broadband subscriptions':df['Fixed broadband subscriptions'].median(),
        'Fixed broadband subscriptions (per 100 people)':df['Fixed broadband subscriptions (per 100 people)'].median(),
        'Fixed telephone subscriptions':df['Fixed telephone subscriptions'].median(),
        'Fixed telephone subscriptions (per 100 people)':df['Fixed telephone subscriptions (per 100 people)'].median()
    },inplace=True
)

In [27]:
df.fillna(
    {
        "GDP (constant 2010 US$)":df['GDP (constant 2010 US$)'].median(),
        "GDP growth (annual %)":df['GDP growth (annual %)'].median(),
        "GDP per capita (constant 2010 US$)":df['GDP per capita (constant 2010 US$)'].median(),
        "GNI (constant 2010 US$)":df['GNI (constant 2010 US$)'].median(),
        'GNI growth (annual %)':df['GNI growth (annual %)'].mean(),
        "GNI per capita (constant 2010 US$)":df['GNI per capita (constant 2010 US$)'].median(),
        "High-technology exports (current US$)":df['High-technology exports (current US$)'].median(),
         "Individuals using the Internet (% of population)":df['Individuals using the Internet (% of population)'].mean()
    },inplace=True
)

In [28]:
df.fillna(
    {
        "Military expenditure (% of GDP)":df['Military expenditure (% of GDP)'].median(),
        "Ratio of female to male labor force participation rate (%) (national estimate)":df["Ratio of female to male labor force participation rate (%) (national estimate)"].mean(),
        "Total reserves (includes gold, current US$)":df["Total reserves (includes gold, current US$)"].median()
    },inplace=True
)